// File: lib/firebase_options.dart
// Konfigurasi Firebase untuk project SkinScan
// Generated by FlutterFire CLI (flutterfire configure)
// Materi: Data Storage Part 4 - Firebase Integration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============================================================
  // PENTING: Ganti nilai-nilai di bawah dengan konfigurasi
  // Firebase project Anda dari Firebase Console
  // https://console.firebase.google.com/
  // ============================================================

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:000000000000:web:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'skinscan-flutter-demo',
    authDomain: 'skinscan-flutter-demo.firebaseapp.com',
    storageBucket: 'skinscan-flutter-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:000000000000:android:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'skinscan-flutter-demo',
    storageBucket: 'skinscan-flutter-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:000000000000:ios:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'skinscan-flutter-demo',
    storageBucket: 'skinscan-flutter-demo.firebasestorage.app',
    iosBundleId: 'com.skinscan.skinscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:000000000000:ios:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'skinscan-flutter-demo',
    storageBucket: 'skinscan-flutter-demo.firebasestorage.app',
    iosBundleId: 'com.skinscan.skinscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:000000000000:windows:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'skinscan-flutter-demo',
    storageBucket: 'skinscan-flutter-demo.firebasestorage.app',
    authDomain: 'skinscan-flutter-demo.firebaseapp.com',
  );
}
